/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LevelService } from "../level.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LevelCreateInput } from "./LevelCreateInput";
import { Level } from "./Level";
import { LevelFindManyArgs } from "./LevelFindManyArgs";
import { LevelWhereUniqueInput } from "./LevelWhereUniqueInput";
import { LevelUpdateInput } from "./LevelUpdateInput";
import { StationFindManyArgs } from "../../station/base/StationFindManyArgs";
import { Station } from "../../station/base/Station";
import { StationWhereUniqueInput } from "../../station/base/StationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LevelControllerBase {
  constructor(
    protected readonly service: LevelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Level })
  @nestAccessControl.UseRoles({
    resource: "Level",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLevel(@common.Body() data: LevelCreateInput): Promise<Level> {
    return await this.service.createLevel({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        order: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Level] })
  @ApiNestedQuery(LevelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Level",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async levels(@common.Req() request: Request): Promise<Level[]> {
    const args = plainToClass(LevelFindManyArgs, request.query);
    return this.service.levels({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        order: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Level })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Level",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async level(
    @common.Param() params: LevelWhereUniqueInput
  ): Promise<Level | null> {
    const result = await this.service.level({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        order: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Level })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Level",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLevel(
    @common.Param() params: LevelWhereUniqueInput,
    @common.Body() data: LevelUpdateInput
  ): Promise<Level | null> {
    try {
      return await this.service.updateLevel({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          order: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Level })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Level",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLevel(
    @common.Param() params: LevelWhereUniqueInput
  ): Promise<Level | null> {
    try {
      return await this.service.deleteLevel({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          order: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/stations")
  @ApiNestedQuery(StationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Station",
    action: "read",
    possession: "any",
  })
  async findStations(
    @common.Req() request: Request,
    @common.Param() params: LevelWhereUniqueInput
  ): Promise<Station[]> {
    const query = plainToClass(StationFindManyArgs, request.query);
    const results = await this.service.findStations(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        level: {
          select: {
            id: true,
          },
        },

        name: true,
        order: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/stations")
  @nestAccessControl.UseRoles({
    resource: "Level",
    action: "update",
    possession: "any",
  })
  async connectStations(
    @common.Param() params: LevelWhereUniqueInput,
    @common.Body() body: StationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stations: {
        connect: body,
      },
    };
    await this.service.updateLevel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/stations")
  @nestAccessControl.UseRoles({
    resource: "Level",
    action: "update",
    possession: "any",
  })
  async updateStations(
    @common.Param() params: LevelWhereUniqueInput,
    @common.Body() body: StationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stations: {
        set: body,
      },
    };
    await this.service.updateLevel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/stations")
  @nestAccessControl.UseRoles({
    resource: "Level",
    action: "update",
    possession: "any",
  })
  async disconnectStations(
    @common.Param() params: LevelWhereUniqueInput,
    @common.Body() body: StationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stations: {
        disconnect: body,
      },
    };
    await this.service.updateLevel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/get-all-levels")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetAllLevels(
    @common.Body()
    body: string
  ): Promise<string> {
    return this.service.GetAllLevels(body);
  }
}
