/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ActivityService } from "../activity.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ActivityCreateInput } from "./ActivityCreateInput";
import { Activity } from "./Activity";
import { ActivityFindManyArgs } from "./ActivityFindManyArgs";
import { ActivityWhereUniqueInput } from "./ActivityWhereUniqueInput";
import { ActivityUpdateInput } from "./ActivityUpdateInput";
import { AchievementFindManyArgs } from "../../achievement/base/AchievementFindManyArgs";
import { Achievement } from "../../achievement/base/Achievement";
import { AchievementWhereUniqueInput } from "../../achievement/base/AchievementWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ActivityControllerBase {
  constructor(
    protected readonly service: ActivityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Activity })
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createActivity(
    @common.Body() data: ActivityCreateInput
  ): Promise<Activity> {
    return await this.service.createActivity({
      data: {
        ...data,

        station: data.station
          ? {
              connect: data.station,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        name: true,
        order: true,

        station: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Activity] })
  @ApiNestedQuery(ActivityFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async activities(@common.Req() request: Request): Promise<Activity[]> {
    const args = plainToClass(ActivityFindManyArgs, request.query);
    return this.service.activities({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        order: true,

        station: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Activity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async activity(
    @common.Param() params: ActivityWhereUniqueInput
  ): Promise<Activity | null> {
    const result = await this.service.activity({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        order: true,

        station: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Activity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateActivity(
    @common.Param() params: ActivityWhereUniqueInput,
    @common.Body() data: ActivityUpdateInput
  ): Promise<Activity | null> {
    try {
      return await this.service.updateActivity({
        where: params,
        data: {
          ...data,

          station: data.station
            ? {
                connect: data.station,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          name: true,
          order: true,

          station: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Activity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteActivity(
    @common.Param() params: ActivityWhereUniqueInput
  ): Promise<Activity | null> {
    try {
      return await this.service.deleteActivity({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          order: true,

          station: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/achievements")
  @ApiNestedQuery(AchievementFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Achievement",
    action: "read",
    possession: "any",
  })
  async findAchievements(
    @common.Req() request: Request,
    @common.Param() params: ActivityWhereUniqueInput
  ): Promise<Achievement[]> {
    const query = plainToClass(AchievementFindManyArgs, request.query);
    const results = await this.service.findAchievements(params.id, {
      ...query,
      select: {
        activity: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        points: true,
        rewardType: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/achievements")
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "update",
    possession: "any",
  })
  async connectAchievements(
    @common.Param() params: ActivityWhereUniqueInput,
    @common.Body() body: AchievementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      achievements: {
        connect: body,
      },
    };
    await this.service.updateActivity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/achievements")
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "update",
    possession: "any",
  })
  async updateAchievements(
    @common.Param() params: ActivityWhereUniqueInput,
    @common.Body() body: AchievementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      achievements: {
        set: body,
      },
    };
    await this.service.updateActivity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/achievements")
  @nestAccessControl.UseRoles({
    resource: "Activity",
    action: "update",
    possession: "any",
  })
  async disconnectAchievements(
    @common.Param() params: ActivityWhereUniqueInput,
    @common.Body() body: AchievementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      achievements: {
        disconnect: body,
      },
    };
    await this.service.updateActivity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/get-all-activities")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetAllActivities(
    @common.Body()
    body: string
  ): Promise<string> {
    return this.service.GetAllActivities(body);
  }
}
